config/routes.rb
Rails.application.routes.draw do
  
  root 'schedules#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'sessions/destroy'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :bookings
  resources :schedules

  

end

app/models/booking.rb
class Booking < ActiveRecord::Base
	belongs_to :user
	belongs_to :schedule
	SEAT_TYPE_LIST = ["Lower Class", "Middle Class", "Higher Class"]
	PAYMENT_METHOD_LIST = ["Cash On Delivery"]
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
    @booking = Booking.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        pdf = ReceiptPdf.new(@booking, view_context)
        send_data pdf.render, filename: "booking.pdf",
                              type: "application/pdf", disposition: "inline"
      end
    end
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)
    @user = User.find(session[:user_id])
    @schedule = Schedule.find(session[:schedule_id])
    respond_to do |format|
      if @booking.save
        session[:schedule_id] = nil
        @schedule.available_seats = @schedule.available_seats.to_i - @booking.no_of_seats_booked.to_i
        @schedule.booked_seats = @schedule.booked_seats.to_i + @booking.no_of_seats_booked.to_i
        @schedule.save!
        UserMailer.receipt_send(@user).deliver
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }

      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:no_of_seats_booked, :seat_type, :cost_of_ticket, :payment_method, :user_id, :schedule_id)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    * Note : Price for each ticket type are mentioned below.
  </p>
  <ol> 
    <li>
      Lower Class : 300
    </li>
    <li>
      Middle Class :500
    </li>
    <li>
      Higher Class :1000
    </li>
  </ol>
  <br><br>
  <div class="field">
    <%= f.label :no_of_seats_booked %><br>
    <%= f.number_field :no_of_seats_booked, :step=>1, :min=>1, :required => true, :class => 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :seat_type %><br>
    <%= f.select(:seat_type, Booking::SEAT_TYPE_LIST, :include_blank => " Select Seat Type" , :required => true, :class => 'form-control') %>
  </div>
  <div class="field">
    <%= f.label :cost_of_ticket %><br>
    <%= f.text_field :cost_of_ticket, :readonly => true, :required => true, :class => 'form-control'%>
  </div>
  <div class="field">
    <%= f.label :payment_method %><br>
    <%= f.select(:payment_method,  Booking::PAYMENT_METHOD_LIST, :include_blank => "Please Select a Payment Type",:required => true, :class => 'form-control') %>
  </div>
  <%= f.hidden_field :user_id, :value => session[:user_id] %>
  <%= f.hidden_field :schedule_id, :value => session[:schedule_id] %>
  <div class="actions">
    <%= f.submit :class => 'btn btn-block form-control'%>
  </div>
<% end %>

<script>


$(document).ready( function ()
{
  
  $('#booking_seat_type').change(function()
  {
    var option = $('#booking_seat_type').val();
    if(option == "Lower Class")
    {
      $('#booking_cost_of_ticket').val(300*($('#booking_no_of_seats_booked').val()));
    }
    else if(option == "Middle Class")
    {
      $('#booking_cost_of_ticket').val(500*($('#booking_no_of_seats_booked').val()));
    }
    else if(option == "Higher Class")
    {
      $('#booking_cost_of_ticket').val(1000*($('#booking_no_of_seats_booked').val())); 
    }   
  });
});

</script>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bookings</h1>

<table>
  <thead>
    <tr>
      <th>No of seats booked</th>
      <th>Seat type</th>
      <th>Cost of ticket</th>
      <th>Payment method</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.no_of_seats_booked %></td>
        <td><%= booking.seat_type %></td>
        <td><%= booking.cost_of_ticket %></td>
        <td><%= booking.payment_method %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<hr>

<br/>
<br/>

<div class="col-md-3"></div>

	<div class="well panel-default col-md-6">
	  	<div class="panel-heading"><center><h3>Book Ticket</h3></center></div>
	  	<div class="panel-body"><br/>
			<div>
			  <% if current_user %>
				   
					<%= render 'form' %>

					<%= link_to 'Back', :controller=> "schedules", :action=> "index" %>

			  <% else %>
			    	<h3>You need to <%= link_to "Sign in", "/auth/facebook", id: "sign_in" %> to book the ticket.</h3>
			  <% end %>
			</div>
		</div>	
	</div>

app/views/bookings/show.html.erb
<hr>
<p id="notice"><%= notice %></p>


<div class="col-md-1"></div>
<div class="well col-md-4">
<p>
  <strong>No of seats booked:</strong>
  <%= @booking.no_of_seats_booked %> 
</p>

<p>
  <strong>Seat type:</strong>
  <%= @booking.seat_type %>
</p>

<p>
  <strong>Cost of ticket:</strong>
  <%= @booking.cost_of_ticket %>
</p>

<p>
  <strong>Payment method:</strong>
  <%= @booking.payment_method %>
</p>
<h4>
<%= link_to 'Print',booking_path(@booking, format: "pdf") %> |
<%= link_to 'Book Another', :controller=> 'bookings', :action=> 'new' %> </h4>
</div>