config/routes.rb
Rails.application.routes.draw do
  
  root 'schedules#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'sessions/destroy'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :bookings
  resources :schedules

  

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
	has_many :bookings
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.order(date: :desc)
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
    @schedule = Schedule.find(params[:id])
    session[:schedule_id] = @schedule.id
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:team_name1, :team_name2, :date, :time, :no_of_seats, :booked_seats, :available_seats)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :team_name1 %><br>
    <% team_array = Team.all.map { |team| [team.name] } %>
    <%= f.select :team_name1,  team_array , :include_blank => "Select Team 1"%>
    
  </div>
  <div class="field">
    <%= f.label :team_name2 %><br>
    <% team_array = Team.all.map { |team| [team.name] } %>
    <%= f.select :team_name2,  team_array , :include_blank => "Select Team 2"%>
    
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.datetime_select :time %>
  </div>
  <div class="field">
    <%= f.label :no_of_seats %><br>
    <%= f.text_field :no_of_seats %>
  </div>
  <%= f.hidden_field :booked_seats %>
  <%= f.hidden_field :available_seats %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
  $(document).ready( function ()
{
  
  $('#schedule_no_of_seats').focusout(function()
  {
    $('#schedule_available_seats').val($('#schedule_no_of_seats').val());   
  });
});
</script>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<p id="notice"><%= notice %></p>
<hr>
<h1 align="center">Listing Schedules</h1>

<table class="table table table-hover table.stripped">
  <thead>
    <tr>
      <th>Team name1</th>
      <th></th>
      <th>Team name2</th>
      <th>Date</th>
      <th>Time</th>
      <th>No of seats</th>
      <th>Available seats</th>
      <th>Booked seats</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.team_name1 %></td>
        <td>Vs</td>
        <td><%= schedule.team_name2 %></td>
        <td><%= schedule.date %></td>
        <td><%= schedule.time.strftime("%I:%M%p") %></td>
        <td><%= schedule.no_of_seats %></td>
        <td><%= schedule.available_seats %></td>
        <td><%= schedule.booked_seats %></td>
        <td><%= link_to 'Show', schedule %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- <%= link_to 'New Schedule', new_schedule_path %> 

app/views/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<hr>
<p id="notice"><%= notice %></p>


<div class="col-md-1"></div>
<div class="well col-md-4">
<p>
  <strong>Team name1:</strong>
  <%= @schedule.team_name1 %>
</p>

<p>
  <strong>Team name2:</strong>
  <%= @schedule.team_name2 %>
</p>

<p>
  <strong>Date:</strong>
  <%= @schedule.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @schedule.time.strftime("%I:%M%p") %>
</p>

<p>
  <strong>No of seats Available:</strong>
  <%= @schedule.available_seats %>
</p>

<h4><%= link_to 'Book Ticket', :controller=> 'bookings', :action=> 'new' %> |
<%= link_to 'Back', schedules_path %></h4>
</div>